# generated by datamodel-codegen:
#   filename:  action.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Action(BaseModel):
    """
    Action
    """

    command: str
    data: dict[str, Any] | None = None
    label: str | None = None
