# generated by datamodel-codegen:
#   filename:  battery.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class LastUpdated(BaseModel):
    """
    Last updated
    """

    is_charging: float | None = None
    percentage: float | None = None


class Battery(BaseModel):
    """
    Battery
    """

    class Config:
        extra = Extra.allow

    id: str | None = Field(None, description="Event ID")
    is_charging: bool | None = None
    percentage: float | None = None
    last_updated: LastUpdated | None = Field(None, description="Last updated")
