# generated by datamodel-codegen:
#   filename:  battery.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class LastUpdated:
    """
    Last updated
    """

    is_charging: float | None = None
    percentage: float | None = None


@dataclass
class Battery:
    """
    Battery
    """

    id: str | None = None
    is_charging: bool | None = None
    percentage: float | None = None
    last_updated: LastUpdated | None = None
