# generated by datamodel-codegen:
#   filename:  display.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class LastUpdated(BaseModel):
    """
    Last updated
    """

    displays: float | None = None


class Display(BaseModel):
    """
    Display
    """

    class Config:
        extra = Extra.allow

    id: str | None = Field(None, description="Event ID")
    displays: list | None = None
    last_updated: LastUpdated | None = Field(None, description="Last updated")
