# generated by datamodel-codegen:
#   filename:  display.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class LastUpdated:
    """
    Last updated
    """

    displays: float | None = None


@dataclass
class Display:
    """
    Display
    """

    id: str | None = None
    displays: list | None = None
    last_updated: LastUpdated | None = None
