# generated by datamodel-codegen:
#   filename:  get_setting.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class GetSetting:
    """
    Get Setting
    """

    setting: str
