# generated by datamodel-codegen:
#   filename:  get_data.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class GetData:
    """
    Get Data
    """

    modules: list
