# generated by datamodel-codegen:
#   filename:  gpu.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class LastUpdated(BaseModel):
    """
    Last updated
    """

    gpus: float | None = None


class Gpu(BaseModel):
    """
    GPU
    """

    class Config:
        extra = Extra.allow

    id: str | None = Field(None, description="Event ID")
    gpus: list | None = None
    last_updated: LastUpdated | None = Field(None, description="Last updated")
