# generated by datamodel-codegen:
#   filename:  gpu.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class LastUpdated:
    """
    Last updated
    """

    gpus: float | None = None


@dataclass
class Gpu:
    """
    GPU
    """

    id: str | None = None
    gpus: list | None = None
    last_updated: LastUpdated | None = None
