# generated by datamodel-codegen:
#   filename:  keyboard_key.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class KeyboardKey:
    """
    Keyboard Key
    """

    key: str
