# generated by datamodel-codegen:
#   filename:  keyboard_text.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class KeyboardText:
    """
    Keyboard Text
    """

    text: str
