# generated by datamodel-codegen:
#   filename:  media_get_files.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class MediaGetFiles:
    """
    Get Files
    """

    base: str
    path: str | None = None
