# generated by datamodel-codegen:
#   filename:  media_get_files.json

from __future__ import annotations

from pydantic import BaseModel


class MediaGetFiles(BaseModel):
    """
    Get Files
    """

    base: str
    path: str | None = None
