# generated by datamodel-codegen:
#   filename:  media_directories.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Directory:
    key: str
    path: str


@dataclass
class MediaDirectories:
    directories: list[Directory]
