# generated by datamodel-codegen:
#   filename:  media_get_file.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class MediaGetFile:
    """
    Get File
    """

    base: str
    path: str
