# generated by datamodel-codegen:
#   filename:  network.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class LastUpdated:
    """
    Last updated
    """

    io_counters_bytes_sent: float | None = None
    io_counters_bytes_recv: float | None = None
    io_counters_packets_sent: float | None = None
    io_counters_packets_recv: float | None = None
    io_counters_errin: float | None = None
    io_counters_errout: float | None = None
    io_counters_dropin: float | None = None
    io_counters_dropout: float | None = None


@dataclass
class Network:
    """
    Network
    """

    id: str | None = None
    io_counters_bytes_sent: int | None = None
    io_counters_bytes_recv: int | None = None
    io_counters_packets_sent: int | None = None
    io_counters_packets_recv: int | None = None
    io_counters_errin: int | None = None
    io_counters_errout: int | None = None
    io_counters_dropin: int | None = None
    io_counters_dropout: int | None = None
    last_updated: LastUpdated | None = None
