# generated by datamodel-codegen:
#   filename:  open_url.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class OpenUrl:
    """
    Open URL
    """

    url: str
