# generated by datamodel-codegen:
#   filename:  open_path.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class OpenPath:
    """
    Open Path
    """

    path: str
