# generated by datamodel-codegen:
#   filename:  register_data_listener.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class RegisterDataListener:
    """
    Register Data Listener
    """

    modules: list
