# generated by datamodel-codegen:
#   filename:  request.json

from __future__ import annotations

from pydantic import BaseModel, Extra, Field


class Request(BaseModel):
    """
    Request
    """

    class Config:
        extra = Extra.allow

    api_key: str | None = Field(None, description="API Key")
    id: str | None = Field(None, description="Message ID")
    event: str = Field(..., description="Event")
