# generated by datamodel-codegen:
#   filename:  response.json

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Extra, Field


class Response(BaseModel):
    """
    Response
    """

    class Config:
        extra = Extra.allow

    id: str | None = Field(None, description="Message ID")
    type: str = Field(..., description="Type")
    subtype: str | None = Field(None, description="Subtype")
    message: str | None = Field(None, description="Message")
    module: str | None = Field(None, description="Module")
    data: Any | None = Field(None, description="Data")
