# generated by datamodel-codegen:
#   filename:  response.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class Response:
    """
    Response
    """

    type: str
    id: str | None = None
    subtype: str | None = None
    message: str | None = None
    module: str | None = None
    data: Any | None = None
