# generated by datamodel-codegen:
#   filename:  sensors.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Sensors:
    """
    Sensors
    """

    id: str | None = None
    last_updated: dict[str, float] | None = None
