# generated by datamodel-codegen:
#   filename:  system.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class LastUpdated:
    """
    Last updated
    """

    boot_time: float
    fqdn: float
    hostname: float
    ip_address_4: float
    mac_address: float
    platform: float
    platform_version: float
    uptime: float
    uuid: float
    version: float
    active_user_id: float | None = None
    active_user_name: float | None = None
    camera_usage: float | None = None
    pending_reboot: float | None = None
    version_latest: float | None = None
    version_newer_available: float | None = None


@dataclass
class System:
    """
    System
    """

    boot_time: float
    fqdn: str
    hostname: str
    ip_address_4: str
    mac_address: str
    platform: str
    platform_version: str
    uptime: float
    uuid: str
    version: str
    id: str | None = None
    active_user_id: float | None = None
    active_user_name: str | None = None
    camera_usage: list[str] | None = None
    pending_reboot: bool | None = None
    version_latest: str | None = None
    version_newer_available: bool | None = None
    last_updated: LastUpdated | None = None
