# generated by datamodel-codegen:
#   filename:  update.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Update:
    """
    Version
    """

    version: str
